name: Project lib check

on:
  push:
    branches:
      - master
      - main
      - v4
      - v4.*
  pull_request:
    branches:
      - master
      - main
      - v4
      - v4.*
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: project check
        run: |
          npm i
          npm run build:icons:prod
          npm run build:lib:prod
          npm run lint:lib
          npm run test:lib:prod
        env:
          CI: true
