name: Project check

on:
  push:
    branches:
      - master
      - v2
  pull_request:
    branches:
      - master
      - v2
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: project check
        run: |
          npm i
          npm run build-lib:prod
          npm run test-lib:prod
#          npm run lint
        env:
          CI: true

  e2e-chrome:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: e2e chrome test
        run: |
          choco install googlechrome --version=114.0.5735.199
          npm i
          npm run build-lib:prod
          npm run e2e
        env:
          BROWSER: chrome
