name: Project check

on:
  push:
    branches:
      - master
      - v2
  pull_request:
    branches:
      - master
      - v2
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Project check
        run: |
          npm run build-lib:prod
          npm run test-lib:prod
#          npm run lint
        env:
          CI: true

  e2e-chrome:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - name: e2e chrome test
        uses: cypress-io/github-action@v6
        timeout-minutes: 5
        with:
          browser: chrome
          build: npm run build-lib:prod
          start: npm start
          wait-on: 'http://localhost:4200'
        env:
          BROWSER: chrome
